[tool.poetry]
name = "ep-bandpass-filter-selector"
version = "0.1.0"
description = ""
authors = ["Yaricp Pisarev <yaricp@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6.9"
numpy = "^1.26.3"
eeg-filters = "^0.0.7"
loguru = "^0.7.2"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.4"


[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"
ruff = "^0.2.1"

[tool.ruff.format]
exclude = ["*.pyi", "*.pyc"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
